### ISSUE TITLE
Error  [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1007)

### ISSUE THREAD

**Issue by boput** [k-takata/vim-kt#68]
Hi,

abort: error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1007)

Command
hg qclone https://hg.osdn.net/view/vim/vim -p http://hg.pf.osdn.net/view/k/k_/k_takata/vim-ktakata-mq vim
fails with above error on my Ubuntu and Debian system.

Checking SSL Certificate reports that license of https://hg.osdn.net/view/vim/vim (resolves to hg.osdn.net) is expired on October 16, 2023.

Last time, on Oct 16 2023 11:48:44 I was able to clone and update vim-kt-64 on Debian and on Ubuntu.

Kindly asking for your comments.

Boput

**Comment by k-takata** [comment]
You can use one of the following URL instead of https://hg.osdn.net/view/vim/vim:
* https://hg.256bit.org/vim
* http://hg.osdn.net/view/vim/vim (Use HTTP instead of HTTPS.)

**Comment by boput** [comment]
Thank you so much. I like using this simplified file structure and upgrade process.

On Feb 18, 2024, at 21:50, K.Takata ***@***.***> wrote:

﻿

You can use one of the following URL instead of https://hg.osdn.net/view/vim/vim:

  *   https://hg.256bit.org/vim
  *   http://hg.osdn.net/view/vim/vim (Use HTTP instead of HTTPS.)
